from __future__ import annotations
import json
import subprocess
import tempfile
from pathlib import Path
from typing import Dict, Optional, Tuple, Union

from videomascot.engine import MascotEngine
from videomascot.models.schema import MascotActionSchema, MascotPlacementSchema, SpeechCue


def probe_video_info(video_path: Union[str, Path]) -> Tuple[int, int, float, float]:
    """Probes video dimensions, duration, and framerate using ffprobe.
    
    Returns: (width, height, duration_sec, fps)
    """
    path_str = str(video_path)
    cmd = [
        "ffprobe", "-v", "error",
        "-select_streams", "v:0",
        "-show_entries", "stream=width,height,r_frame_rate,duration",
        "-show_entries", "format=duration",
        "-of", "json",
        path_str
    ]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=15)
    if res.returncode != 0:
        raise RuntimeError(f"ffprobe failed to probe '{path_str}': {res.stderr}")
        
    data = json.loads(res.stdout)
    stream = data.get("streams", [{}])[0]
    fmt = data.get("format", {})
    
    w = int(stream.get("width", 1920))
    h = int(stream.get("height", 1080))
    
    # Framerate calculation (e.g. '24/1' or '30000/1001')
    r_fps = stream.get("r_frame_rate", "24/1")
    if "/" in r_fps:
        num, den = r_fps.split("/")
        fps = float(num) / max(float(den), 1.0)
    else:
        fps = float(r_fps)
        
    # Duration
    dur_str = stream.get("duration") or fmt.get("duration") or "3.0"
    duration = float(dur_str)
    
    return (w, h, duration, fps)


class VideoOverlayCompositor:
    """In-memory zero-disk video overlay compositor.
    
    Streams transparent mascot frames into FFmpeg to composite them directly
    over background video clips (e.g. generated by video-pipe).
    """

    def __init__(self, engine: MascotEngine) -> None:
        self.engine = engine

    @classmethod
    def from_bundle_dir(cls, bundle_dir: Union[str, Path]) -> VideoOverlayCompositor:
        engine = MascotEngine.from_bundle_dir(bundle_dir)
        return cls(engine=engine)

    def overlay_onto_video(
        self,
        input_video: Union[str, Path],
        output_video: Union[str, Path],
        action: Optional[MascotActionSchema] = None,
        scene_dict: Optional[Dict] = None,
        audio_path: Optional[Union[str, Path]] = None,
        vtt_path: Optional[Union[str, Path]] = None,
        crf: int = 20,
        preset: str = "medium",
        mute_base_audio: bool = True
    ) -> Path:
        """Composites an animated transparent mascot stream directly onto an input video file."""
        in_path = Path(input_video)
        out_path = Path(output_video)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        
        if not in_path.exists():
            raise FileNotFoundError(f"Input video not found: {in_path}")
            
        vw, vh, duration, fps = probe_video_info(in_path)
        int_fps = max(1, int(round(fps)))
        
        # 1. Resolve MascotAction
        if action is not None:
            act = action
        elif scene_dict is not None:
            m_data = scene_dict.get("mascot") or {}
            act = MascotActionSchema.model_validate(m_data)
        else:
            act = MascotActionSchema()
            
        if not act.enabled:
            # If mascot is explicitly disabled, pass-through copy
            copy_cmd = ["ffmpeg", "-y", "-i", str(in_path), "-c:v", "copy"]
            if mute_base_audio:
                copy_cmd.append("-an")
            else:
                copy_cmd.extend(["-c:a", "copy"])
            copy_cmd.append(str(out_path))
            subprocess.run(copy_cmd, check=True, capture_output=True)
            return out_path

        # 2. Calculate mascot scaled dimensions & placement coordinates
        scale_ratio = act.placement.scale
        mascot_target_h = max(64, int(round(vh * scale_ratio)))
        
        # Maintain native aspect ratio of mascot canvas
        orig_w, orig_h = self.engine.canvas_size
        aspect = orig_w / max(orig_h, 1)
        mascot_target_w = int(round(mascot_target_h * aspect))
        
        pos_x, pos_y = act.placement.calculate_position(
            video_size=(vw, vh),
            mascot_size=(mascot_target_w, mascot_target_h)
        )

        # 3. Setup FFmpeg subprocess with stdin rawvideo pipe and temporary stderr file to avoid pipe buffer deadlock
        ffmpeg_cmd = [
            "ffmpeg", "-y",
            "-i", str(in_path), # [0:v] base video
            "-f", "rawvideo",
            "-pix_fmt", "rgba",
            "-s", f"{mascot_target_w}x{mascot_target_h}",
            "-r", str(int_fps),
            "-i", "pipe:0",     # [1:v] transparent mascot stream
            "-filter_complex",
            f"[0:v][1:v]overlay=x={pos_x}:y={pos_y}:eof_action=pass:shortest=1[outv]",
            "-map", "[outv]",
        ]

        if not mute_base_audio:
            ffmpeg_cmd.extend(["-map", "0:a?", "-c:a", "copy"])
        else:
            ffmpeg_cmd.append("-an")

        ffmpeg_cmd.extend([
            "-c:v", "libx264",
            "-pix_fmt", "yuv420p",
            "-preset", preset,
            "-crf", str(crf),
            str(out_path)
        ])

        resolved_vtt = vtt_path
        if resolved_vtt is None and audio_path:
            candidate = Path(audio_path).with_suffix(".vtt")
            if candidate.exists():
                resolved_vtt = candidate

        stream = self.engine.stream_scene(
            action=act,
            duration=duration,
            fps=int_fps,
            vtt_path=resolved_vtt,
            target_size=(mascot_target_w, mascot_target_h)
        )

        with tempfile.TemporaryFile(mode="w+b") as stderr_file:
            proc = subprocess.Popen(ffmpeg_cmd, stdin=subprocess.PIPE, stderr=stderr_file)
            try:
                for frame_bytes in stream:
                    proc.stdin.write(frame_bytes)
                proc.stdin.close()
                proc.wait(timeout=60)
            except Exception as e:
                proc.kill()
                raise RuntimeError(f"Video overlay FFmpeg process failed: {e}")

            if proc.returncode != 0:
                stderr_file.seek(0)
                err_text = stderr_file.read().decode("utf-8", errors="replace")
                raise RuntimeError(f"FFmpeg overlay error (code {proc.returncode}): {err_text}")

        return out_path
